version: '3'

volumes:
  db:

services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/code/
    command: ./docker-entrypoint.sh dev
    depends_on:
      - db

  db:
    env_file:
      - .env
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/