[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Bartosz Woźniak <bartoszwoz0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Django = "4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
