def get_dummy_api_response_for_today(lat, lon):
    return {
        "coord": {"lon": lon, "lat": lat},
        "weather": [
            {"id": 803, "main": "Clouds", "description": "broken clouds", "icon": "04d"}
        ],
        "base": "stations",
        "main": {
            "temp": 123123298.2,
            "feels_like": 298.88,
            "temp_min": 298.2,
            "temp_max": 298.2,
            "pressure": 1011,
            "humidity": 81,
            "sea_level": 1011,
            "grnd_level": 1011,
        },
        "visibility": 10000,
        "wind": {"speed": 7.15, "deg": 224, "gust": 7.31},
        "clouds": {"all": 55},
        "dt": 567456,
        "sys": {"sunrise": 123234, "sunset": 345456567},
        "timezone": 0,
        "id": 0,
        "name": "",
        "cod": 200,
    }


def get_dummy_api_response_for_next_days(lat, lon):
    return {
        "cod": "200",
        "message": 0,
        "cnt": 40,
        "list": [
            {
                "dt": 1664636400,
                "main": {
                    "temp": 295.03,
                    "feels_like": 293.77,
                    "temp_min": 292.7,
                    "temp_max": 295.03,
                    "pressure": 1024,
                    "sea_level": 1024,
                    "grnd_level": 1004,
                    "humidity": 19,
                    "temp_kf": 2.33,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03n",
                    }
                ],
                "clouds": {"all": 25},
                "wind": {"speed": 4.98, "deg": 117, "gust": 8.32},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-01 15:00:00",
            },
            {
                "dt": 1664647200,
                "main": {
                    "temp": 291.39,
                    "feels_like": 290.16,
                    "temp_min": 288.99,
                    "temp_max": 291.39,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 34,
                    "temp_kf": 2.4,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03n",
                    }
                ],
                "clouds": {"all": 29},
                "wind": {"speed": 7.68, "deg": 120, "gust": 12.12},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-01 18:00:00",
            },
            {
                "dt": 1664658000,
                "main": {
                    "temp": 286.88,
                    "feels_like": 285.59,
                    "temp_min": 286.88,
                    "temp_max": 286.88,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1004,
                    "humidity": 49,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 93},
                "wind": {"speed": 7, "deg": 122, "gust": 11.63},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-01 21:00:00",
            },
            {
                "dt": 1664668800,
                "main": {
                    "temp": 286.1,
                    "feels_like": 284.65,
                    "temp_min": 286.1,
                    "temp_max": 286.1,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1004,
                    "humidity": 46,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 96},
                "wind": {"speed": 5.09, "deg": 128, "gust": 9.32},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-02 00:00:00",
            },
            {
                "dt": 1664679600,
                "main": {
                    "temp": 286.04,
                    "feels_like": 284.4,
                    "temp_min": 286.04,
                    "temp_max": 286.04,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1004,
                    "humidity": 39,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 86},
                "wind": {"speed": 5.62, "deg": 128, "gust": 9.4},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-02 03:00:00",
            },
            {
                "dt": 1664690400,
                "main": {
                    "temp": 290.35,
                    "feels_like": 288.75,
                    "temp_min": 290.35,
                    "temp_max": 290.35,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1004,
                    "humidity": 24,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 66},
                "wind": {"speed": 7.48, "deg": 128, "gust": 8.1},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-02 06:00:00",
            },
            {
                "dt": 1664701200,
                "main": {
                    "temp": 293.23,
                    "feels_like": 291.89,
                    "temp_min": 293.23,
                    "temp_max": 293.23,
                    "pressure": 1023,
                    "sea_level": 1023,
                    "grnd_level": 1003,
                    "humidity": 23,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 8},
                "wind": {"speed": 6.75, "deg": 121, "gust": 6.71},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-02 09:00:00",
            },
            {
                "dt": 1664712000,
                "main": {
                    "temp": 293.3,
                    "feels_like": 292.02,
                    "temp_min": 293.3,
                    "temp_max": 293.3,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 25,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 5},
                "wind": {"speed": 6.5, "deg": 118, "gust": 6.52},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-02 12:00:00",
            },
            {
                "dt": 1664722800,
                "main": {
                    "temp": 290.34,
                    "feels_like": 288.92,
                    "temp_min": 290.34,
                    "temp_max": 290.34,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 31,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 0},
                "wind": {"speed": 6.91, "deg": 104, "gust": 10.51},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-02 15:00:00",
            },
            {
                "dt": 1664733600,
                "main": {
                    "temp": 286.43,
                    "feels_like": 284.73,
                    "temp_min": 286.43,
                    "temp_max": 286.43,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 35,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 0},
                "wind": {"speed": 7.94, "deg": 109, "gust": 11.11},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-02 18:00:00",
            },
            {
                "dt": 1664744400,
                "main": {
                    "temp": 284.09,
                    "feels_like": 282.36,
                    "temp_min": 284.09,
                    "temp_max": 284.09,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1000,
                    "humidity": 43,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 1},
                "wind": {"speed": 6.77, "deg": 110, "gust": 11.62},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-02 21:00:00",
            },
            {
                "dt": 1664755200,
                "main": {
                    "temp": 283.22,
                    "feels_like": 281.51,
                    "temp_min": 283.22,
                    "temp_max": 283.22,
                    "pressure": 1019,
                    "sea_level": 1019,
                    "grnd_level": 999,
                    "humidity": 47,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 801,
                        "main": "Clouds",
                        "description": "few clouds",
                        "icon": "02n",
                    }
                ],
                "clouds": {"all": 19},
                "wind": {"speed": 5.26, "deg": 105, "gust": 10.71},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-03 00:00:00",
            },
            {
                "dt": 1664766000,
                "main": {
                    "temp": 282.98,
                    "feels_like": 280.28,
                    "temp_min": 282.98,
                    "temp_max": 282.98,
                    "pressure": 1019,
                    "sea_level": 1019,
                    "grnd_level": 999,
                    "humidity": 45,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03d",
                    }
                ],
                "clouds": {"all": 44},
                "wind": {"speed": 5.68, "deg": 106, "gust": 11.52},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-03 03:00:00",
            },
            {
                "dt": 1664776800,
                "main": {
                    "temp": 288.48,
                    "feels_like": 286.83,
                    "temp_min": 288.48,
                    "temp_max": 288.48,
                    "pressure": 1019,
                    "sea_level": 1019,
                    "grnd_level": 999,
                    "humidity": 29,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 801,
                        "main": "Clouds",
                        "description": "few clouds",
                        "icon": "02d",
                    }
                ],
                "clouds": {"all": 24},
                "wind": {"speed": 8.94, "deg": 115, "gust": 10.21},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-03 06:00:00",
            },
            {
                "dt": 1664787600,
                "main": {
                    "temp": 291.77,
                    "feels_like": 290.21,
                    "temp_min": 291.77,
                    "temp_max": 291.77,
                    "pressure": 1018,
                    "sea_level": 1018,
                    "grnd_level": 998,
                    "humidity": 20,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 6},
                "wind": {"speed": 8.08, "deg": 114, "gust": 8.6},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-03 09:00:00",
            },
            {
                "dt": 1664798400,
                "main": {
                    "temp": 292.71,
                    "feels_like": 291.17,
                    "temp_min": 292.71,
                    "temp_max": 292.71,
                    "pressure": 1018,
                    "sea_level": 1018,
                    "grnd_level": 998,
                    "humidity": 17,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 6},
                "wind": {"speed": 7.91, "deg": 108, "gust": 8.51},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-03 12:00:00",
            },
            {
                "dt": 1664809200,
                "main": {
                    "temp": 289.44,
                    "feels_like": 287.8,
                    "temp_min": 289.44,
                    "temp_max": 289.44,
                    "pressure": 1019,
                    "sea_level": 1019,
                    "grnd_level": 999,
                    "humidity": 26,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03n",
                    }
                ],
                "clouds": {"all": 42},
                "wind": {"speed": 7.64, "deg": 94, "gust": 12.03},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-03 15:00:00",
            },
            {
                "dt": 1664820000,
                "main": {
                    "temp": 285.91,
                    "feels_like": 284.16,
                    "temp_min": 285.91,
                    "temp_max": 285.91,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 35,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 71},
                "wind": {"speed": 7.66, "deg": 100, "gust": 12.01},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-03 18:00:00",
            },
            {
                "dt": 1664830800,
                "main": {
                    "temp": 284.46,
                    "feels_like": 282.74,
                    "temp_min": 284.46,
                    "temp_max": 284.46,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 42,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 100},
                "wind": {"speed": 5.61, "deg": 96, "gust": 11.2},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-03 21:00:00",
            },
            {
                "dt": 1664841600,
                "main": {
                    "temp": 283.67,
                    "feels_like": 281.87,
                    "temp_min": 283.67,
                    "temp_max": 283.67,
                    "pressure": 1021,
                    "sea_level": 1021,
                    "grnd_level": 1001,
                    "humidity": 42,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 97},
                "wind": {"speed": 4.49, "deg": 100, "gust": 9.22},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-04 00:00:00",
            },
            {
                "dt": 1664852400,
                "main": {
                    "temp": 283.48,
                    "feels_like": 281.64,
                    "temp_min": 283.48,
                    "temp_max": 283.48,
                    "pressure": 1022,
                    "sea_level": 1022,
                    "grnd_level": 1002,
                    "humidity": 41,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 83},
                "wind": {"speed": 5.19, "deg": 101, "gust": 11.01},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-04 03:00:00",
            },
            {
                "dt": 1664863200,
                "main": {
                    "temp": 289.86,
                    "feels_like": 288.29,
                    "temp_min": 289.86,
                    "temp_max": 289.86,
                    "pressure": 1023,
                    "sea_level": 1023,
                    "grnd_level": 1003,
                    "humidity": 27,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 83},
                "wind": {"speed": 8.99, "deg": 113, "gust": 10.91},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-04 06:00:00",
            },
            {
                "dt": 1664874000,
                "main": {
                    "temp": 294.02,
                    "feels_like": 292.58,
                    "temp_min": 294.02,
                    "temp_max": 294.02,
                    "pressure": 1022,
                    "sea_level": 1022,
                    "grnd_level": 1002,
                    "humidity": 16,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 61},
                "wind": {"speed": 9.56, "deg": 116, "gust": 10.5},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-04 09:00:00",
            },
            {
                "dt": 1664884800,
                "main": {
                    "temp": 294.64,
                    "feels_like": 293.16,
                    "temp_min": 294.64,
                    "temp_max": 294.64,
                    "pressure": 1022,
                    "sea_level": 1022,
                    "grnd_level": 1002,
                    "humidity": 12,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03d",
                    }
                ],
                "clouds": {"all": 35},
                "wind": {"speed": 9.07, "deg": 117, "gust": 9.91},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-04 12:00:00",
            },
            {
                "dt": 1664895600,
                "main": {
                    "temp": 290.35,
                    "feels_like": 288.6,
                    "temp_min": 290.35,
                    "temp_max": 290.35,
                    "pressure": 1024,
                    "sea_level": 1024,
                    "grnd_level": 1003,
                    "humidity": 18,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 1},
                "wind": {"speed": 7.17, "deg": 97, "gust": 11.91},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-04 15:00:00",
            },
            {
                "dt": 1664906400,
                "main": {
                    "temp": 286.42,
                    "feels_like": 284.77,
                    "temp_min": 286.42,
                    "temp_max": 286.42,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1004,
                    "humidity": 37,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 0},
                "wind": {"speed": 7.41, "deg": 101, "gust": 13.02},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-04 18:00:00",
            },
            {
                "dt": 1664917200,
                "main": {
                    "temp": 285.01,
                    "feels_like": 283.32,
                    "temp_min": 285.01,
                    "temp_max": 285.01,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 41,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 7},
                "wind": {"speed": 6.22, "deg": 106, "gust": 12.6},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-04 21:00:00",
            },
            {
                "dt": 1664928000,
                "main": {
                    "temp": 284.3,
                    "feels_like": 282.59,
                    "temp_min": 284.3,
                    "temp_max": 284.3,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 43,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01n",
                    }
                ],
                "clouds": {"all": 7},
                "wind": {"speed": 5.45, "deg": 115, "gust": 11.51},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-05 00:00:00",
            },
            {
                "dt": 1664938800,
                "main": {
                    "temp": 284.26,
                    "feels_like": 282.34,
                    "temp_min": 284.26,
                    "temp_max": 284.26,
                    "pressure": 1026,
                    "sea_level": 1026,
                    "grnd_level": 1005,
                    "humidity": 35,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 4},
                "wind": {"speed": 6.02, "deg": 118, "gust": 12.33},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-05 03:00:00",
            },
            {
                "dt": 1664949600,
                "main": {
                    "temp": 291.59,
                    "feels_like": 289.83,
                    "temp_min": 291.59,
                    "temp_max": 291.59,
                    "pressure": 1026,
                    "sea_level": 1026,
                    "grnd_level": 1006,
                    "humidity": 13,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 3},
                "wind": {"speed": 8.83, "deg": 124, "gust": 11.04},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-05 06:00:00",
            },
            {
                "dt": 1664960400,
                "main": {
                    "temp": 295.8,
                    "feels_like": 294.33,
                    "temp_min": 295.8,
                    "temp_max": 295.8,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 8,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 6},
                "wind": {"speed": 8.95, "deg": 126, "gust": 9.62},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-05 09:00:00",
            },
            {
                "dt": 1664971200,
                "main": {
                    "temp": 296.06,
                    "feels_like": 294.62,
                    "temp_min": 296.06,
                    "temp_max": 296.06,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 8,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 800,
                        "main": "Clear",
                        "description": "clear sky",
                        "icon": "01d",
                    }
                ],
                "clouds": {"all": 7},
                "wind": {"speed": 8.07, "deg": 123, "gust": 8.55},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-05 12:00:00",
            },
            {
                "dt": 1664982000,
                "main": {
                    "temp": 291.64,
                    "feels_like": 289.83,
                    "temp_min": 291.64,
                    "temp_max": 291.64,
                    "pressure": 1026,
                    "sea_level": 1026,
                    "grnd_level": 1006,
                    "humidity": 11,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 801,
                        "main": "Clouds",
                        "description": "few clouds",
                        "icon": "02n",
                    }
                ],
                "clouds": {"all": 11},
                "wind": {"speed": 6.17, "deg": 112, "gust": 11.5},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-05 15:00:00",
            },
            {
                "dt": 1664992800,
                "main": {
                    "temp": 288.38,
                    "feels_like": 286.64,
                    "temp_min": 288.38,
                    "temp_max": 288.38,
                    "pressure": 1027,
                    "sea_level": 1027,
                    "grnd_level": 1006,
                    "humidity": 26,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 56},
                "wind": {"speed": 7.24, "deg": 113, "gust": 13.52},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-05 18:00:00",
            },
            {
                "dt": 1665003600,
                "main": {
                    "temp": 286.83,
                    "feels_like": 284.98,
                    "temp_min": 286.83,
                    "temp_max": 286.83,
                    "pressure": 1027,
                    "sea_level": 1027,
                    "grnd_level": 1006,
                    "humidity": 28,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 72},
                "wind": {"speed": 6.6, "deg": 122, "gust": 13.01},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-05 21:00:00",
            },
            {
                "dt": 1665014400,
                "main": {
                    "temp": 285.75,
                    "feels_like": 283.8,
                    "temp_min": 285.75,
                    "temp_max": 285.75,
                    "pressure": 1026,
                    "sea_level": 1026,
                    "grnd_level": 1006,
                    "humidity": 28,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04n",
                    }
                ],
                "clouds": {"all": 58},
                "wind": {"speed": 5.79, "deg": 130, "gust": 11.61},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "n"},
                "dt_txt": "2022-10-06 00:00:00",
            },
            {
                "dt": 1665025200,
                "main": {
                    "temp": 285.51,
                    "feels_like": 283.38,
                    "temp_min": 285.51,
                    "temp_max": 285.51,
                    "pressure": 1027,
                    "sea_level": 1027,
                    "grnd_level": 1006,
                    "humidity": 22,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 94},
                "wind": {"speed": 5.13, "deg": 135, "gust": 10.8},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-06 03:00:00",
            },
            {
                "dt": 1665036000,
                "main": {
                    "temp": 292.61,
                    "feels_like": 290.87,
                    "temp_min": 292.61,
                    "temp_max": 292.61,
                    "pressure": 1027,
                    "sea_level": 1027,
                    "grnd_level": 1006,
                    "humidity": 10,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 804,
                        "main": "Clouds",
                        "description": "overcast clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 97},
                "wind": {"speed": 8.04, "deg": 143, "gust": 10.2},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-06 06:00:00",
            },
            {
                "dt": 1665046800,
                "main": {
                    "temp": 297.01,
                    "feels_like": 295.63,
                    "temp_min": 297.01,
                    "temp_max": 297.01,
                    "pressure": 1025,
                    "sea_level": 1025,
                    "grnd_level": 1005,
                    "humidity": 7,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 803,
                        "main": "Clouds",
                        "description": "broken clouds",
                        "icon": "04d",
                    }
                ],
                "clouds": {"all": 67},
                "wind": {"speed": 8.2, "deg": 150, "gust": 9},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-06 09:00:00",
            },
            {
                "dt": 1665057600,
                "main": {
                    "temp": 297.51,
                    "feels_like": 296.16,
                    "temp_min": 297.51,
                    "temp_max": 297.51,
                    "pressure": 1024,
                    "sea_level": 1024,
                    "grnd_level": 1004,
                    "humidity": 6,
                    "temp_kf": 0,
                },
                "weather": [
                    {
                        "id": 802,
                        "main": "Clouds",
                        "description": "scattered clouds",
                        "icon": "03d",
                    }
                ],
                "clouds": {"all": 38},
                "wind": {"speed": 6.7, "deg": 157, "gust": 7.23},
                "visibility": 10000,
                "pop": 0,
                "sys": {"pod": "d"},
                "dt_txt": "2022-10-06 12:00:00",
            },
        ],
        "city": {
            "id": 608879,
            "name": "Mangistauskaya Oblast’",
            "coord": {"lat": lat, "lon": lon},
            "country": "KZ",
            "population": 0,
            "timezone": 18000,
            "sunrise": 1664590624,
            "sunset": 1664632939,
        },
    }
